### ISSUE TITLE
mui-chips-input version 2.0.2 issues with React-dom

### ISSUE THREAD

**Issue by jjlatval** [viclafouch/mui-chips-input#32]
**Describe the bug**

I get the following error message on mui-chips-input 2.0.2 (but not with earlier version 2.0.1):

Server Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**To Reproduce**
1. Just try out the example of README.md, i.e.:

```import React from 'react'
import { MuiChipsInput } from 'mui-chips-input'

const MyComponent = () => {
  const [chips, setChips] = React.useState([])

  const handleChange = (newChips) => {
    setChips(newChips)
  }

  return (
    <MuiChipsInput value={chips} onChange={handleChange} />
  )
}
```

**Expected behavior**
The component is supposed to render without errors.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey version 12.3.1
 - Browser Chrome version 114.0.5735.133
 - Next 13.1.6
 - React 18.2.0
 - React-dom 18.2.0

**Additional context**

I am running this in a NextJS application. Also the Code Sandbox runs into the same issue: https://codesandbox.io/s/mui-chips-input-fsf9p3

Downgrading to mui-chips-input version 2.0.1 solves the issue for me locally on my NextJS application.

Here is the full output of what happens with React-dom-server and Next:

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at /Users/user1/some_project/node_modules/mui-chips-input/dist/mui-chips-input.umd.js:52:82
    at /Users/user1/some_project/node_modules/mui-chips-input/dist/mui-chips-input.umd.js:52:2801
    at div
    at div
    at div
    at div
    at Search (webpack-internal:///./src/components/Search.tsx:87:88)
    at ProtectedRoute (webpack-internal:///./src/components/ProtectedRoute.tsx:15:27)
    at SearchPage
    at PinboardContextProvider (webpack-internal:///./src/context/PinboardContext.tsx:22:36)
    at UserAuthContextProvider (webpack-internal:///./src/context/UserAuthContext.tsx:22:36)
    at some_project (webpack-internal:///./src/pages/_app.tsx:46:24)
    at StyleRegistry (/Users/user1/some_project/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/Users/user1/some_project/node_modules/next/dist/shared/lib/router/adapters.js:78:11)
    at AppContainer (/Users/user1/some_project/node_modules/next/dist/server/render.js:341:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/user1/some_project/node_modules/next/dist/server/render.js:377:57)
    at div
    at Body (/Users/user1/some_project/node_modules/next/dist/server/render.js:677:21)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at /Users/user1/some_project/node_modules/mui-chips-input/dist/mui-chips-input.umd.js:52:82
    at /Users/user1/some_project/node_modules/mui-chips-input/dist/mui-chips-input.umd.js:52:2801
    at div
    at div
    at div
    at div
    at Search (webpack-internal:///./src/components/Search.tsx:87:88)
    at ProtectedRoute (webpack-internal:///./src/components/ProtectedRoute.tsx:15:27)
    at SearchPage
    at PinboardContextProvider (webpack-internal:///./src/context/PinboardContext.tsx:22:36)
    at UserAuthContextProvider (webpack-internal:///./src/context/UserAuthContext.tsx:22:36)
    at some_project (webpack-internal:///./src/pages/_app.tsx:46:24)
    at StyleRegistry (/Users/user1/some_project/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/Users/user1/some_project/node_modules/next/dist/shared/lib/router/adapters.js:78:11)
    at AppContainer (/Users/user1/some_project/node_modules/next/dist/server/render.js:341:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/user1/some_project/node_modules/next/dist/server/render.js:377:57)
    at div
    at Body (/Users/user1/some_project/node_modules/next/dist/server/render.js:677:21)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at /Users/user1/some_project/node_modules/mui-chips-input/dist/mui-chips-input.umd.js:52:82
    at /Users/user1/some_project/node_modules/mui-chips-input/dist/mui-chips-input.umd.js:52:2801
    at div
    at div
    at div
    at div
    at Search (webpack-internal:///./src/components/Search.tsx:87:88)
    at ProtectedRoute (webpack-internal:///./src/components/ProtectedRoute.tsx:15:27)
    at SearchPage
    at PinboardContextProvider (webpack-internal:///./src/context/PinboardContext.tsx:22:36)
    at UserAuthContextProvider (webpack-internal:///./src/context/UserAuthContext.tsx:22:36)
    at some_project (webpack-internal:///./src/pages/_app.tsx:46:24)
    at StyleRegistry (/Users/user1/some_project/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/Users/user1/some_project/node_modules/next/dist/shared/lib/router/adapters.js:78:11)
    at AppContainer (/Users/user1/some_project/node_modules/next/dist/server/render.js:341:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/user1/some_project/node_modules/next/dist/server/render.js:377:57)
    at div
    at Body (/Users/user1/some_project/node_modules/next/dist/server/render.js:677:21)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
- error Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/user1/some_project/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11) {
  digest: undefined
}

```

**Comment by napiersystems** [comment]
Experiencing the same issue as @jjlatval on Ubuntu within a standard React app on React: 18.2.0 & React-dom: 18.2.0.

Downgraded to 2.0.1 did not resolve the issue either.

The issue appears once the component is pulled within the UI, but the individual component within my storybook repo works fine on it's own. If I am able to find more debugging information then I will post.

**Comment by viclafouch** [comment]
Hello ! Fixed in last version !
